function aMiGetScopes()

stack = dbstack(1);

message = '[';

if numel(stack) >= 1
    message = [message, ...
               '{"name": "local", ', ...
                '"variablesReference": 0, ', ...
                '"expensive": false}, '];
end

if numel(stack) > 1
    message = [message, ...
               '{"name": "caller", ', ...
                '"variablesReference": 0, ', ...
                '"expensive": false}, '];
end 

message = [message, ...
           '{"name": "global", ', ...
            '"variablesReference": 0, ', ...
            '"expensive": false}]'];

disp(message);